Theory guide: properties
feos-org/feos pull request #100
Opened 2022-12-26 14:56 UTC by prehner

closes #99

2022-12-27 14:10 UTC, g-bauer requested changes
Great documentation. Would it be helpful to have details about the implementation (caching, duals) in the theory guide (maybe but not necessarily in this document)?

2022-12-27 14:10 UTC, g-bauer commented on docs/theory/eos/properties.md
> +| Internal energy $U$ | A+TS | yes |
`$A + TS$`

2022-12-27 14:10 UTC, g-bauer commented on docs/theory/eos/properties.md
> +| Gibbs energy $G$ | A+pV | yes |
`$A+pV$`

2022-12-27 14:51 UTC, prehner commented on docs/theory/eos/properties.md
> +$$A^\mathrm{ig}(T,V,N_i)=RT\sum_iN_i\left(\ln\left(\frac{N_i\Lambda_i^3}{V}\right)-1\right)$$(eqn:a_ig)
Technically you are right. However, in this context, I prefer using R over kB. What about using n instead of N for mole numbers?

2022-12-27 14:56 UTC, prehner commented
> Great documentation. Would it be helpful to have details about the implementation (caching, duals) in the theory guide (maybe but not necessarily in this document)?

The rust guide already goes into some detail about the implementation of states including, e.g., the cache. Maybe link to it in this document?

2022-12-28 12:45 UTC, g-bauer commented on docs/theory/eos/properties.md
> +$$A^\mathrm{ig}(T,V,N_i)=RT\sum_iN_i\left(\ln\left(\frac{N_i\Lambda_i^3}{V}\right)-1\right)$$(eqn:a_ig)
Sounds good.

2023-01-02 12:38 UTC, g-bauer approved these changes

2023-01-02 12:39 UTC, merged